name: php-test

on:
  workflow_dispatch: # Allows you to trigger the job manually from the GitHub UI

jobs:
  rclone-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rclone
        run: |
          php -v
